In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

2022-09-26 15:05:00.453402: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
df = pd.read_csv("Resources/HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df_cat = df.dtypes[df.dtypes == 'object'].index.tolist()

In [4]:
df[df_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [5]:
enc = OneHotEncoder(sparse=False)

encode_df = pd.DataFrame(enc.fit_transform(df[df_cat]))

encode_df.columns = enc.get_feature_names(df_cat)

encode_df.head()

/Users/johnwhendricks/opt/anaconda3/envs/mlenv/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
df = df.merge(encode_df, left_index=True, right_index=True)

df = df.drop(df_cat, 1)

df.head()

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_74557/3100034761.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(df_cat, 1)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
y = df['Attrition_Yes'].values

X = df.drop(['Attrition_Yes','Attrition_No'], 1).values

X_train, X_test, y_train, y_test = train_test_split(X, y)

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_74557/3504684544.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = df.drop(['Attrition_Yes','Attrition_No'], 1).values

In [8]:
scaler = StandardScaler()

X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
num_input_features = len(X_train[0])
hidden_nodes1 = 8
hidden_nodes2 = 5

nn = tf.keras.models.Sequential([
    
    tf.keras.layers.Dense(units = hidden_nodes1, input_dim= num_input_features, activation='relu'),
    tf.keras.layers.Dense(units= hidden_nodes2, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
    
])

nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

2022-09-26 15:05:04.279304: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [10]:
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [11]:
fit_model = nn.fit(X_train, y_train, epochs=100)

Epoch 1/100
35/35 [==============================] - 0s 1ms/step - loss: 844.2482 - accuracy: 0.1670
Epoch 2/100
35/35 [==============================] - 0s 1ms/step - loss: 476.6827 - accuracy: 0.1670
Epoch 3/100
35/35 [==============================] - 0s 1ms/step - loss: 160.7520 - accuracy: 0.2142
Epoch 4/100
35/35 [==============================] - 0s 1ms/step - loss: 10.2585 - accuracy: 0.7541
Epoch 5/100
35/35 [==============================] - 0s 1ms/step - loss: 2.4048 - accuracy: 0.8230
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6113 - accuracy: 0.8258
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 1.1477 - accuracy: 0.8267
Epoch 8/100
35/35 [==============================] - 0s 1ms/step - loss: 0.8256 - accuracy: 0.8294
Epoch 9/100
35/35 [==============================] - 0s 1ms/step - loss: 0.6927 - accuracy: 0.8294
Epoch 10/100
35/35 [==============================] - 0s 1ms/step - loss: 0.6058 - accuracy: 0.8303
Epoch 11/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5625 - accuracy: 0.8312
Epoch 12/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5285 - accuracy: 0.8321
Epoch 13/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5192 - accuracy: 0.8330
Epoch 14/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5095 - accuracy: 0.8330
Epoch 15/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5016 - accuracy: 0.8339
Epoch 16/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4997 - accuracy: 0.8339
Epoch 17/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.8339
Epoch 18/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4980 - accuracy: 0.8339
Epoch 19/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4960 - accuracy: 0.8339
Epoch 20/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4967 - accuracy: 0.8339
Epoch 21/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4922 - accuracy: 0.8339
Epoch 22/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4919 - accuracy: 0.8339
Epoch 23/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4907 - accuracy: 0.8339
Epoch 24/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4891 - accuracy: 0.8339
Epoch 25/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4922 - accuracy: 0.8339
Epoch 26/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4895 - accuracy: 0.8339
Epoch 27/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4877 - accuracy: 0.8339
Epoch 28/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4845 - accuracy: 0.8339
Epoch 29/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4870 - accuracy: 0.8339
Epoch 30/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4874 - accuracy: 0.8339
Epoch 31/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4851 - accuracy: 0.8339
Epoch 32/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4862 - accuracy: 0.8339
Epoch 33/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4824 - accuracy: 0.8339
Epoch 34/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4813 - accuracy: 0.8339
Epoch 35/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4785 - accuracy: 0.8339
Epoch 36/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4763 - accuracy: 0.8339
Epoch 37/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4781 - accuracy: 0.8339
Epoch 38/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4818 - accuracy: 0.8339
Epoch 39/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4777 - accuracy: 0.8339
Epoch 40/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4753 - accuracy: 0.8339
Epoch 41/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4721 - accuracy: 0.8339
Epoch 42/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4752 - accuracy: 0.8339
Epoch 43/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4741 - accuracy: 0.8339
Epoch 44/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4716 - accuracy: 0.8339
Epoch 45/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4713 - accuracy: 0.8339
Epoch 46/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4756 - accuracy: 0.8339
Epoch 47/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4758 - accuracy: 0.8339
Epoch 48/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4712 - accuracy: 0.8339
Epoch 49/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4737 - accuracy: 0.8339
Epoch 50/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4760 - accuracy: 0.8339
Epoch 51/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4733 - accuracy: 0.8339
Epoch 52/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4829 - accuracy: 0.8339
Epoch 53/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4689 - accuracy: 0.8339
Epoch 54/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4649 - accuracy: 0.8339
Epoch 55/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4681 - accuracy: 0.8339
Epoch 56/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4672 - accuracy: 0.8339
Epoch 57/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4701 - accuracy: 0.8339
Epoch 58/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4704 - accuracy: 0.8339
Epoch 59/100
35/35 [==============================] - 0s 989us/step - loss: 0.4658 - accuracy: 0.8339
Epoch 60/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4667 - accuracy: 0.8339
Epoch 61/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4647 - accuracy: 0.8339
Epoch 62/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4649 - accuracy: 0.8339
Epoch 63/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4674 - accuracy: 0.8339
Epoch 64/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4686 - accuracy: 0.8339
Epoch 65/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4609 - accuracy: 0.8339
Epoch 66/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4607 - accuracy: 0.8339
Epoch 67/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4603 - accuracy: 0.8339
Epoch 68/100
35/35 [==============================] - 0s 981us/step - loss: 0.4599 - accuracy: 0.8339
Epoch 69/100
35/35 [==============================] - 0s 946us/step - loss: 0.4619 - accuracy: 0.8339
Epoch 70/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4639 - accuracy: 0.8339
Epoch 71/100
35/35 [==============================] - 0s 915us/step - loss: 0.4610 - accuracy: 0.8339
Epoch 72/100
35/35 [==============================] - 0s 969us/step - loss: 0.4597 - accuracy: 0.8339
Epoch 73/100
35/35 [==============================] - 0s 935us/step - loss: 0.4600 - accuracy: 0.8339
Epoch 74/100
35/35 [==============================] - 0s 943us/step - loss: 0.4562 - accuracy: 0.8339
Epoch 75/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4652 - accuracy: 0.8339
Epoch 76/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4561 - accuracy: 0.8339
Epoch 77/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4590 - accuracy: 0.8339
Epoch 78/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4556 - accuracy: 0.8339
Epoch 79/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4611 - accuracy: 0.8339
Epoch 80/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4570 - accuracy: 0.8339
Epoch 81/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4585 - accuracy: 0.8339
Epoch 82/100

35/35 [==============================] - 0s 1ms/step - loss: 0.4556 - accuracy: 0.8339
Epoch 83/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.8339
Epoch 84/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4527 - accuracy: 0.8339
Epoch 85/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4536 - accuracy: 0.8339
Epoch 86/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4542 - accuracy: 0.8339
Epoch 87/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4513 - accuracy: 0.8339
Epoch 88/100
35/35 [==============================] - 0s 973us/step - loss: 0.4503 - accuracy: 0.8339
Epoch 89/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4513 - accuracy: 0.8339
Epoch 90/100
35/35 [==============================] - 0s 997us/step - loss: 0.4505 - accuracy: 0.8339
Epoch 91/100
35/35 [==============================] - 0s 933us/step - loss: 0.4516 - accuracy: 0.8339
Epoch 92/100
35/35 [==============================] - 0s 963us/step - loss: 0.4605 - accuracy: 0.8339
Epoch 93/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4495 - accuracy: 0.8339
Epoch 94/100
35/35 [==============================] - 0s 937us/step - loss: 0.4515 - accuracy: 0.8339
Epoch 95/100
35/35 [==============================] - 0s 916us/step - loss: 0.4517 - accuracy: 0.8339
Epoch 96/100
35/35 [==============================] - 0s 981us/step - loss: 0.4504 - accuracy: 0.8339
Epoch 97/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4537 - accuracy: 0.8339
Epoch 98/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4488 - accuracy: 0.8339
Epoch 99/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4510 - accuracy: 0.8339
Epoch 100/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4500 - accuracy: 0.8339

In [12]:
model_loss, model_accuracy = nn.evaluate(X_test, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.3953 - accuracy: 0.8587 - 130ms/epoch - 11ms/step
Loss: 0.39529913663864136, Accuracy: 0.8586956262588501